version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo Finished installing
      - npm run test

  build:
    commands:
      - echo Build started on `date`
      - npm test
  artifacts:
  files:
    - '**/*'
